'use client';
import { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth, db } from '@/lib/firebase'; import { Movie } from '@/lib/types'; import Nav from '@/components/Nav'; import { useRouter } from 'next/navigation';
const empty={title:'',description:'',genre:'Action',language:'Hindi',year:'2026',posterUrl:'',videoUrl:'',source:'Licensed'};
export default function Admin(){ const [user,setUser]=useState<any>(null); const [movies,setMovies]=useState<Movie[]>([]); const [form,setForm]=useState<Movie>(empty); const [msg,setMsg]=useState(''); const r=useRouter();
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u); if(!u) r.push('/login')}),[r]);
 async function load(){const q=query(collection(db,'movies'),orderBy('createdAt','desc')); const snap=await getDocs(q); setMovies(snap.docs.map(d=>({id:d.id,...d.data()} as Movie)));}
 useEffect(()=>{if(user)load()},[user]);
 async function save(e:any){e.preventDefault(); await addDoc(collection(db,'movies'),{...form,createdAt:serverTimestamp()}); setForm(empty); setMsg('Movie added successfully'); load();}
 async function remove(id:string){await deleteDoc(doc(db,'movies',id)); load();}
 if(!user)return <><Nav/><div className="container">Loading...</div></>;
 return <><Nav/><div className="container"><div className="row" style={{justifyContent:'space-between'}}><h1>Admin Dashboard</h1><button className="btn secondary" onClick={()=>signOut(auth)}>Logout</button></div><form className="form" onSubmit={save}><h2>Add Licensed Movie</h2>{msg&&<div className="success">{msg}</div>}<input className="input" placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/><div className="row"><input className="input" placeholder="Genre" value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}/><input className="input" placeholder="Language" value={form.language} onChange={e=>setForm({...form,language:e.target.value})}/><input className="input" placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></div><input className="input" placeholder="Poster image URL" value={form.posterUrl} onChange={e=>setForm({...form,posterUrl:e.target.value})}/><input className="input" placeholder="Official licensed video URL (.mp4/.m3u8)" value={form.videoUrl} onChange={e=>setForm({...form,videoUrl:e.target.value})} required/><input className="input" placeholder="Source / License note" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/><button className="btn">Add Movie</button></form><div className="table"><h2>Movies</h2>{movies.map(m=><div className="item" key={m.id}><b>{m.title}</b><p className="muted">{m.genre} • {m.language} • {m.source}</p><button className="btn secondary" onClick={()=>remove(m.id!)}>Delete</button></div>)}</div></div></>}
